import {
  Proveedor,
  Producto,
  Cliente,
  Cotizacion,
  OrdenCompra,
  FacturaCompra,
  ComprobanteSunat,
  OrdenTrabajo,
  Usuario,
} from '@/types/erp';

export const INITIAL_USUARIOS: Usuario[] = [
  {
    id: 'usr_admin',
    nombre: 'Ing. Carlos Mendoza',
    email: 'gerencia@agrofertilperu.com',
    rol: 'ADMIN',
    telefono: '+51 987 654 321',
  },
  {
    id: 'usr_tecnico_1',
    nombre: 'Juan Quispe Ramos (Técnico Senior)',
    email: 'jquispe@agrofertilperu.com',
    rol: 'TECNICO',
    telefono: '+51 976 112 334',
  },
  {
    id: 'usr_tecnico_2',
    nombre: 'Marcos Benites (Técnico de Campo)',
    email: 'mbenites@agrofertilperu.com',
    rol: 'TECNICO',
    telefono: '+51 945 889 900',
  },
];

export const INITIAL_PROVEEDORES: Proveedor[] = [
  {
    id: 'prov_1',
    ruc: '20512345678',
    razon_social: 'RIEGO & TECNOLOGÍA HIDRÁULICA S.A.C.',
    email: 'ventas@riegotechperu.com',
    telefono: '(01) 456-7890',
    contacto: 'Ing. Fernando Salazar',
    departamento: 'LIMA',
    provincia: 'LIMA',
    direccion: 'Av. Industrial 1240, Cercado de Lima, Lima',
    dias_entrega_estimados: 6, // Proveedor de Lima (Despacho interprovincial: 5-7 días)
    costo_flete_base: 180,
  },
  {
    id: 'prov_2',
    ruc: '20601234991',
    razon_social: 'PLÁSTICOS Y TUBERÍAS AGRÍCOLAS PERÚ E.I.R.L.',
    email: 'comercial@plasticosagri.pe',
    telefono: '+51 987 111 222',
    contacto: 'Mariela Cornejo',
    departamento: 'LIMA',
    provincia: 'LIMA',
    direccion: 'Jr. Los Claveles 450, Lurín, Lima',
    dias_entrega_estimados: 5,
    costo_flete_base: 120,
  },
  {
    id: 'prov_3',
    ruc: '20498765432',
    razon_social: 'AGROQUÍMICA & FERTILIZANTES DEL VALLE S.A.',
    email: 'pedidos@agroquimicavalle.com',
    telefono: '(056) 234-567',
    contacto: 'Dr. Roberto Chinchay',
    departamento: 'ICA',
    provincia: 'ICA',
    direccion: 'Panamericana Sur Km 298, Ica',
    dias_entrega_estimados: 1, // Proveedor local (Entrega rápida en 24-48 horas)
    costo_flete_base: 30,
  },
  {
    id: 'prov_4',
    ruc: '20556677889',
    razon_social: 'AUTOMATIZACIÓN & SENSORES DEL PERÚ S.A.C.',
    email: 'soporte@sensoresagri.com',
    telefono: '+51 999 444 333',
    contacto: 'Ing. Pamela Vega',
    departamento: 'LIMA',
    provincia: 'LIMA',
    direccion: 'Av. Aviación 3200, San Borja, Lima',
    dias_entrega_estimados: 7, // Sensores importados / Despacho Lima
    costo_flete_base: 150,
  },
];

export const INITIAL_PRODUCTOS: Producto[] = [
  {
    id: 'prod_1',
    codigo: 'MESA-FERT-04',
    nombre: 'Mesa de Fertilización Automatizada 4 Canales (Inyectores Venturi + Bombas)',
    descripcion: 'Mesa completa con estructura de acero inoxidable, manifold de 4 canales de inyección, rotámetros 100-1000 L/h, válvula reguladora de presión y panel eléctrico.',
    categoria: 'EQUIPO_FERTILIZACION',
    precio_venta: 18500,
    costo_compra: 13200,
    proveedor_id: 'prov_1',
    proveedor_nombre: 'RIEGO & TECNOLOGÍA HIDRÁULICA S.A.C.',
    stock: 4,
    unidad_medida: 'UNID',
  },
  {
    id: 'prod_2',
    codigo: 'BOMB-DOSIF-1HP',
    nombre: 'Bomba Booster Dosificadora de Inyección 1.5 HP Acero Inox AISI 316',
    descripcion: 'Bomba multicelular horizontal de alta resistencia para inyección de fertilizantes ácidos y sales.',
    categoria: 'BOMBAS_INYECTORES',
    precio_venta: 3400,
    costo_compra: 2450,
    proveedor_id: 'prov_1',
    proveedor_nombre: 'RIEGO & TECNOLOGÍA HIDRÁULICA S.A.C.',
    stock: 8,
    unidad_medida: 'UNID',
  },
  {
    id: 'prod_3',
    codigo: 'VENT-MAZZEI-2IN',
    nombre: 'Inyector Venturi Mazzei 2" con Válvula Check y Medidor de Flujo',
    descripcion: 'Inyector de alta eficiencia para mezclado homogéneo de soluciones nutritivas.',
    categoria: 'BOMBAS_INYECTORES',
    precio_venta: 850,
    costo_compra: 580,
    proveedor_id: 'prov_1',
    proveedor_nombre: 'RIEGO & TECNOLOGÍA HIDRÁULICA S.A.C.',
    stock: 15,
    unidad_medida: 'UNID',
  },
  {
    id: 'prod_4',
    codigo: 'TUB-PVC-C80-3IN',
    nombre: 'Tubería PVC C-80 Presión 3" x 6m para Manifold Hidráulico',
    descripcion: 'Tubería cédula 80 resistente a altas presiones y sustancias corrosivas.',
    categoria: 'TUBERIAS_VALVULAS',
    precio_venta: 210,
    costo_compra: 145,
    proveedor_id: 'prov_2',
    proveedor_nombre: 'PLÁSTICOS Y TUBERÍAS AGRÍCOLAS PERÚ E.I.R.L.',
    stock: 45,
    unidad_medida: 'MTR',
  },
  {
    id: 'prod_5',
    codigo: 'VALV-SOL-24V-2IN',
    nombre: 'Válvula Solenoide Eléctrica Bermad 2" 24VAC con Control de Caudal',
    descripcion: 'Válvula hidráulica de diafragma para apertura y cierre programado por sectores.',
    categoria: 'TUBERIAS_VALVULAS',
    precio_venta: 590,
    costo_compra: 410,
    proveedor_id: 'prov_2',
    proveedor_nombre: 'PLÁSTICOS Y TUBERÍAS AGRÍCOLAS PERÚ E.I.R.L.',
    stock: 22,
    unidad_medida: 'UNID',
  },
  {
    id: 'prod_6',
    codigo: 'FERT-NITRATO-CAL',
    nombre: 'Nitrato de Calcio Soluble Grado Fertirriego (Saco 25 Kg)',
    descripcion: 'Fertilizante 100% soluble de rápida asimilación para nutrición vegetal y fertirriego.',
    categoria: 'INSUMOS_QUIMICOS',
    precio_venta: 145,
    costo_compra: 98,
    proveedor_id: 'prov_3',
    proveedor_nombre: 'AGROQUÍMICA & FERTILIZANTES DEL VALLE S.A.',
    stock: 120,
    unidad_medida: 'SACO',
  },
  {
    id: 'prod_7',
    codigo: 'ACID-FOSFOR-85',
    nombre: 'Ácido Fosfórico al 85% para Limpieza de Goteros y Acidificación (Bidón 35 Kg)',
    descripcion: 'Acidificante de alta pureza para regulación de pH y aporte de fósforo asimilable.',
    categoria: 'INSUMOS_QUIMICOS',
    precio_venta: 320,
    costo_compra: 220,
    proveedor_id: 'prov_3',
    proveedor_nombre: 'AGROQUÍMICA & FERTILIZANTES DEL VALLE S.A.',
    stock: 35,
    unidad_medida: 'BIDON',
  },
  {
    id: 'prod_8',
    codigo: 'CTRL-AGRI-EC-PH',
    nombre: 'Controlador de Fertirriego Programable con Sensores de pH y Conductividad (EC)',
    descripcion: 'Unidad de control inteligente con pantalla táctil, puertos RS485 y calibración automática.',
    categoria: 'SENSORES_CONTROLADORES',
    precio_venta: 7800,
    costo_compra: 5400,
    proveedor_id: 'prov_4',
    proveedor_nombre: 'AUTOMATIZACIÓN & SENSORES DEL PERÚ S.A.C.',
    stock: 5,
    unidad_medida: 'UNID',
  },
];

export const INITIAL_CLIENTES: Cliente[] = [
  {
    id: 'cli_1',
    tipo_doc: 'RUC',
    num_doc: '20608912345',
    razon_social: 'AGRÍCOLA DEL SUR S.A.C.',
    direccion: 'Fundo San José Lote 14, Valle de Chincha, Ica',
    email: 'compras@agricoladelsur.com.pe',
    telefono: '+51 956 123 456',
    estado_contribuyente: 'ACTIVO',
    condicion: 'HABIDO',
    departamento: 'Ica',
    provincia: 'Chincha',
    distrito: 'Chincha Baja',
  },
  {
    id: 'cli_2',
    tipo_doc: 'RUC',
    num_doc: '20509876123',
    razon_social: 'CAMPOS DE VIRÚ AGROEXPORT S.A.',
    direccion: 'Av. Panamericana Norte Km 520, Virú, La Libertad',
    email: 'contacto@camposdeviru.pe',
    telefono: '+51 944 887 766',
    estado_contribuyente: 'ACTIVO',
    condicion: 'HABIDO',
    departamento: 'La Libertad',
    provincia: 'Virú',
    distrito: 'Virú',
  },
  {
    id: 'cli_3',
    tipo_doc: 'DNI',
    num_doc: '45892104',
    razon_social: 'RODRÍGUEZ HUAMÁN JORGE LUIS',
    direccion: 'Calle Los Olivos Mz B Lt 4, Huaral, Lima',
    email: 'jorge.rodriguez@gmail.com',
    telefono: '+51 988 332 211',
    estado_contribuyente: 'ACTIVO',
    condicion: 'HABIDO',
    departamento: 'Lima',
    provincia: 'Huaral',
    distrito: 'Huaral',
  },
];

export const INITIAL_COTIZACIONES: Cotizacion[] = [
  {
    id: 'cot_1',
    numero: 'COT-2026-001',
    cliente_id: 'cli_1',
    cliente_tipo_doc: 'RUC',
    cliente_num_doc: '20608912345',
    cliente_razon_social: 'AGRÍCOLA DEL SUR S.A.C.',
    cliente_direccion: 'Fundo San José Lote 14, Valle de Chincha, Ica',
    cliente_email: 'compras@agricoladelsur.com.pe',
    cliente_telefono: '+51 956 123 456',
    tipo_operacion: 'VENTA_ARMADO',
    estado: 'EN_INSTALACION',
    subtotal: 30500,
    igv: 5490,
    total: 35990,
    moneda: 'PEN',
    incluye_mano_obra: true,
    costo_mano_obra: 2500,
    orden_trabajo_id: 'ot_1',
    fecha: '2026-08-15',
    observaciones: 'Instalación de mesa de fertilización 4 inyectores + controlador EC/pH en cabezal de riego 2.',
    detalles: [
      {
        id: 'det_1',
        producto_id: 'prod_1',
        producto_codigo: 'MESA-FERT-04',
        producto_nombre: 'Mesa de Fertilización Automatizada 4 Canales (Inyectores Venturi + Bombas)',
        proveedor_id: 'prov_1',
        cantidad: 1,
        precio_unitario: 18500,
        costo_unitario: 13200,
        subtotal: 18500,
      },
      {
        id: 'det_2',
        producto_id: 'prod_8',
        producto_codigo: 'CTRL-AGRI-EC-PH',
        producto_nombre: 'Controlador de Fertirriego Programable con Sensores de pH y Conductividad (EC)',
        proveedor_id: 'prov_4',
        cantidad: 1,
        precio_unitario: 7800,
        costo_unitario: 5400,
        subtotal: 7800,
      },
      {
        id: 'det_3',
        producto_id: 'prod_5',
        producto_codigo: 'VALV-SOL-24V-2IN',
        producto_nombre: 'Válvula Solenoide Eléctrica Bermad 2" 24VAC con Control de Caudal',
        proveedor_id: 'prov_2',
        cantidad: 2,
        precio_unitario: 590,
        costo_unitario: 410,
        subtotal: 1180,
      },
      {
        id: 'det_4',
        producto_id: 'prod_4',
        producto_codigo: 'TUB-PVC-C80-3IN',
        producto_nombre: 'Tubería PVC C-80 Presión 3" x 6m para Manifold Hidráulico',
        proveedor_id: 'prov_2',
        cantidad: 2,
        precio_unitario: 210,
        costo_unitario: 145,
        subtotal: 420,
      },
    ],
  },
  {
    id: 'cot_2',
    numero: 'COT-2026-002',
    cliente_id: 'cli_2',
    cliente_tipo_doc: 'RUC',
    cliente_num_doc: '20509876123',
    cliente_razon_social: 'CAMPOS DE VIRÚ AGROEXPORT S.A.',
    cliente_direccion: 'Av. Panamericana Norte Km 520, Virú, La Libertad',
    cliente_email: 'contacto@camposdeviru.pe',
    cliente_telefono: '+51 944 887 766',
    tipo_operacion: 'SOLO_VENTA',
    estado: 'EN_COMPRAS',
    subtotal: 11650,
    igv: 2097,
    total: 13747,
    moneda: 'PEN',
    incluye_mano_obra: false,
    costo_mano_obra: 0,
    fecha: '2026-08-18',
    observaciones: 'Suministro bajo pedido de insumos y repuestos para temporada de fertirriego arándanos.',
    detalles: [
      {
        id: 'det_5',
        producto_id: 'prod_6',
        producto_codigo: 'FERT-NITRATO-CAL',
        producto_nombre: 'Nitrato de Calcio Soluble Grado Fertirriego (Saco 25 Kg)',
        proveedor_id: 'prov_3',
        cantidad: 50,
        precio_unitario: 145,
        costo_unitario: 98,
        subtotal: 7250,
      },
      {
        id: 'det_6',
        producto_id: 'prod_7',
        producto_codigo: 'ACID-FOSFOR-85',
        producto_nombre: 'Ácido Fosfórico al 85% para Limpieza de Goteros y Acidificación (Bidón 35 Kg)',
        proveedor_id: 'prov_3',
        cantidad: 10,
        precio_unitario: 320,
        costo_unitario: 220,
        subtotal: 3200,
      },
      {
        id: 'det_7',
        producto_id: 'prod_3',
        producto_codigo: 'VENT-MAZZEI-2IN',
        producto_nombre: 'Inyector Venturi Mazzei 2" con Válvula Check y Medidor de Flujo',
        proveedor_id: 'prov_1',
        cantidad: 2,
        precio_unitario: 850,
        costo_unitario: 580,
        subtotal: 1700,
      },
    ],
  },
  {
    id: 'cot_3',
    numero: 'COT-2026-003',
    cliente_id: 'cli_3',
    cliente_tipo_doc: 'DNI',
    cliente_num_doc: '45892104',
    cliente_razon_social: 'RODRÍGUEZ HUAMÁN JORGE LUIS',
    cliente_direccion: 'Calle Los Olivos Mz B Lt 4, Huaral, Lima',
    cliente_email: 'jorge.rodriguez@gmail.com',
    cliente_telefono: '+51 988 332 211',
    tipo_operacion: 'SOLO_VENTA',
    estado: 'PENDIENTE',
    subtotal: 4250,
    igv: 765,
    total: 5015,
    moneda: 'PEN',
    incluye_mano_obra: false,
    costo_mano_obra: 0,
    fecha: '2026-08-20',
    observaciones: 'Cotización en vivo generada desde portal web público.',
    detalles: [
      {
        id: 'det_8',
        producto_id: 'prod_2',
        producto_codigo: 'BOMB-DOSIF-1HP',
        producto_nombre: 'Bomba Booster Dosificadora de Inyección 1.5 HP Acero Inox AISI 316',
        proveedor_id: 'prov_1',
        cantidad: 1,
        precio_unitario: 3400,
        costo_unitario: 2450,
        subtotal: 3400,
      },
      {
        id: 'det_9',
        producto_id: 'prod_3',
        producto_codigo: 'VENT-MAZZEI-2IN',
        producto_nombre: 'Inyector Venturi Mazzei 2" con Válvula Check y Medidor de Flujo',
        proveedor_id: 'prov_1',
        cantidad: 1,
        precio_unitario: 850,
        costo_unitario: 580,
        subtotal: 850,
      },
    ],
  },
];

export const INITIAL_ORDENES_COMPRA: OrdenCompra[] = [
  {
    id: 'oc_1',
    numero: 'OC-2026-001',
    proveedor_id: 'prov_1',
    proveedor_ruc: '20512345678',
    proveedor_razon_social: 'RIEGO & TECNOLOGÍA HIDRÁULICA S.A.C.',
    proveedor_email: 'ventas@riegotechperu.com',
    cotizacion_id: 'cot_1',
    cotizacion_numero: 'COT-2026-001',
    fecha: '2026-08-16',
    estado: 'RECIBIDO',
    monto_total: 13200,
    moneda: 'PEN',
    factura_proveedor_num: 'F001-0004521',
    fecha_recepcion: '2026-08-18',
    detalles: [
      {
        id: 'oc_det_1',
        producto_id: 'prod_1',
        producto_codigo: 'MESA-FERT-04',
        producto_nombre: 'Mesa de Fertilización Automatizada 4 Canales (Inyectores Venturi + Bombas)',
        cantidad: 1,
        costo_unitario: 13200,
        subtotal: 13200,
      },
    ],
  },
  {
    id: 'oc_2',
    numero: 'OC-2026-002',
    proveedor_id: 'prov_4',
    proveedor_ruc: '20556677889',
    proveedor_razon_social: 'AUTOMATIZACIÓN & SENSORES DEL PERÚ S.A.C.',
    proveedor_email: 'soporte@sensoresagri.com',
    cotizacion_id: 'cot_1',
    cotizacion_numero: 'COT-2026-001',
    fecha: '2026-08-16',
    estado: 'RECIBIDO',
    monto_total: 5400,
    moneda: 'PEN',
    factura_proveedor_num: 'F002-0001890',
    fecha_recepcion: '2026-08-18',
    detalles: [
      {
        id: 'oc_det_2',
        producto_id: 'prod_8',
        producto_codigo: 'CTRL-AGRI-EC-PH',
        producto_nombre: 'Controlador de Fertirriego Programable con Sensores de pH y Conductividad (EC)',
        cantidad: 1,
        costo_unitario: 5400,
        subtotal: 5400,
      },
    ],
  },
  {
    id: 'oc_3',
    numero: 'OC-2026-003',
    proveedor_id: 'prov_3',
    proveedor_ruc: '20498765432',
    proveedor_razon_social: 'AGROQUÍMICA & FERTILIZANTES DEL VALLE S.A.',
    proveedor_email: 'pedidos@agroquimicavalle.com',
    cotizacion_id: 'cot_2',
    cotizacion_numero: 'COT-2026-002',
    fecha: '2026-08-19',
    estado: 'ENVIADO',
    monto_total: 7100,
    moneda: 'PEN',
    detalles: [
      {
        id: 'oc_det_3',
        producto_id: 'prod_6',
        producto_codigo: 'FERT-NITRATO-CAL',
        producto_nombre: 'Nitrato de Calcio Soluble Grado Fertirriego (Saco 25 Kg)',
        cantidad: 50,
        costo_unitario: 98,
        subtotal: 4900,
      },
      {
        id: 'oc_det_4',
        producto_id: 'prod_7',
        producto_codigo: 'ACID-FOSFOR-85',
        producto_nombre: 'Ácido Fosfórico al 85% para Limpieza de Goteros y Acidificación (Bidón 35 Kg)',
        cantidad: 10,
        costo_unitario: 220,
        subtotal: 2200,
      },
    ],
  },
];

export const INITIAL_FACTURAS_COMPRAS: FacturaCompra[] = [
  {
    id: 'fc_1',
    proveedor_id: 'prov_1',
    proveedor_nombre: 'RIEGO & TECNOLOGÍA HIDRÁULICA S.A.C.',
    orden_compra_id: 'oc_1',
    orden_compra_numero: 'OC-2026-001',
    numero_factura: 'F001-0004521',
    fecha_emision: '2026-08-18',
    monto_total: 13200,
    moneda: 'PEN',
    estado_pago: 'PAGADO',
  },
  {
    id: 'fc_2',
    proveedor_id: 'prov_4',
    proveedor_nombre: 'AUTOMATIZACIÓN & SENSORES DEL PERÚ S.A.C.',
    orden_compra_id: 'oc_2',
    orden_compra_numero: 'OC-2026-002',
    numero_factura: 'F002-0001890',
    fecha_emision: '2026-08-18',
    monto_total: 5400,
    moneda: 'PEN',
    estado_pago: 'PENDIENTE',
  },
];

export const INITIAL_COMPROBANTES_SUNAT: ComprobanteSunat[] = [
  {
    id: 'cpe_1',
    cotizacion_id: 'cot_1',
    tipo_comprobante: 'FACTURA',
    serie: 'F001',
    numero: '00000142',
    cliente_tipo_doc: 'RUC',
    cliente_num_doc: '20608912345',
    cliente_razon_social: 'AGRÍCOLA DEL SUR S.A.C.',
    cliente_direccion: 'Fundo San José Lote 14, Valle de Chincha, Ica',
    subtotal: 15250,
    igv: 2745,
    total: 17995,
    moneda: 'PEN',
    xml_url: '/api/sunat/xml/F001-00000142.xml',
    cdr_url: '/api/sunat/cdr/R-F001-00000142.zip',
    pdf_url: '/api/sunat/pdf/F001-00000142.pdf',
    estado_sunat: 'ACEPTADO',
    hash_cpe: 'x4H7bQ912kLkOp0qA+nU7y89d=',
    qr_data: '20601234567|01|F001|00000142|2745.00|17995.00|2026-08-16|6|20608912345|',
    fecha_emision: '2026-08-16',
    observaciones_sunat: 'El comprobante ha sido ACEPTADO por SUNAT con código de respuesta 0.',
  },
];

export const INITIAL_ORDENES_TRABAJO: OrdenTrabajo[] = [
  {
    id: 'ot_1',
    codigo: 'OT-2026-001',
    cotizacion_id: 'cot_1',
    cotizacion_numero: 'COT-2026-001',
    cliente_nombre: 'AGRÍCOLA DEL SUR S.A.C.',
    cliente_telefono: '+51 956 123 456',
    ubicacion_fundo: 'Fundo San José Lote 14, Valle de Chincha, Ica (Cabezal de Riego 2)',
    tecnico_id: 'usr_tecnico_1',
    tecnico_nombre: 'Juan Quispe Ramos (Técnico Senior)',
    fecha_programada: '2026-08-19',
    estado: 'EN_PROCESO',
    observaciones: 'Instalación y calibración de mesa de fertilización con 4 líneas Venturi.',
    bitacora: [
      {
        id: 'bit_1',
        orden_trabajo_id: 'ot_1',
        hito: '1. Fijación de Estructura y Manifold Principal',
        nota: 'Llegada al fundo 8:30 AM. Nivelación del terreno, anclaje de la base de acero inox e instalación del manifold de PVC C-80.',
        foto_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
        fecha_registro: '2026-08-19',
        hora_registro: '09:45 AM',
      },
      {
        id: 'bit_2',
        orden_trabajo_id: 'ot_1',
        hito: '2. Montaje de Bombas y Conexiones Hidráulicas',
        nota: 'Conexión de la bomba booster 1.5HP con válvulas check y rotámetros de 1000 L/h. Sellado con teflón de alta densidad.',
        foto_url: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80',
        fecha_registro: '2026-08-19',
        hora_registro: '01:15 PM',
      },
      {
        id: 'bit_3',
        orden_trabajo_id: 'ot_1',
        hito: '3. Pruebas Hidráulicas de Presión (4.2 Bar)',
        nota: 'Prueba de estanqueidad sin fugas. Caudales de inyección estables a 450 L/h por canal.',
        foto_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=600&q=80',
        materiales_extra: '2x Adaptador macho 2" C-80, 1x Niple galvanizado 1"',
        fecha_registro: '2026-08-19',
        hora_registro: '04:30 PM',
      },
    ],
  },
];
